### ISSUE TITLE
Unable to receive any data

### ISSUE THREAD

**Issue by m0lucky** [MikeLauer/F1-2021-Telemetry#1]
I built the app with Visual Studio.. first time doing this.. but have i maybe missed a setting to allow connections? I disabled my firewall completely to try this. Ip and port are correct. I have tried the UDP format of 2020 and 2021. Any suggestions? App looks good by the way.

**Comment by MikeLauer** [comment]
Hey m0lucky!
You do NOT have to disable firewall to run this program!

- When you're starting the program for the first time, Windows should automatically ask for permission to start an UDP Server. Did you get that popup window and pressed "allow" or smiliar?
- Do you get any error message from visual studio that might help us to resolve this issue?
- UDP Format 2021 is correct. Others won't work. I also recommend using the current version that I just pushed.

What I suspect (I thought VS would handle this automatically) is that a packet is missing. You can try the following:
- Open the project in Visual Studio
- Click on "Project" -> "NuGet Packet Manager"
- Search for "TimHanewich.Toolkit"
- Select Version 3.0.0 and install that
- Try to compile and run the program

Keep me updated,
Mike
